/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Jan 18 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <spi_config.h>
#include <max7219.h>
#include <stdlib.h>
#include <delay.h>

struct cell 
{
   uint8_t previous_state;
   uint8_t current_state;
   uint8_t next_state;
};


int main (void)
{ 
// Write your code here

   uint8_t led_matrix[8][8] = {
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
   };

   int i,j;

   spi_init();
   max7219_init();




   while (1)
   {
      for (i = 0; i < 8; i++)
      {
         for (j = 0; j < 8; j++)
         {
            led_matrix[i][j] = playboard[i][j].current_state;
         }
      }

      max7219_load(led_matrix);
      max7219_refresh();

      for (i = 0; i < 8; i++)
      {
         for (j = 0; j < 8; j++)
         {
            
            playboard[i][j].previous_state = playboard[i][j].current_state;

            if (playboard[i][j].previous_state == 1)
            {
               playboard[i][j].current_state = 0;
            }
            else
            { 
               if (i-1 >= 0)
               {
                  if (playboard[i-1][j].previous_state == 1)
                  {
                     playboard[i][j].current_state = 1;
                  }
               }
               if (j-1 >= 0)
               {
                  if (playboard[i][j-1].previous_state == 1)
                  {
                     playboard[i][j].current_state = 1;
                  }
               }
               if (i-1 >= 0 && j-1 >= 0)
               {
                  if (playboard[i-1][j-1].previous_state == 1)
                  {
                     playboard[i][j].current_state = 1;
                  }
               }
            }
         }
      }
      delay_ms(1000);
   }

}   
