/* Main.c file generated by New Project wizard
 *
 * Created:   Tue Jan 18 2022
 * Processor: STM32F103C6
 * Compiler:  Keil for ARM
 */

#include <stm32f103x6.h>
#include <spi_config.h>
#include <max7219.h>
#include <stdlib.h>
#include <string.h>

void delay_ms(uint16_t time)
{  //Funcion de retardo
volatile unsigned long l = 0;
uint16_t i;

for(i = 0; i < time; i++)
{
for(l = 0; l < 800; l++);
}
}

int main (void)
{ 
// Write your code here

   uint8_t playboard[8][8] = {
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
                           {0},
   };

   uint8_t matrix_lines[8] = {0};
   
   int i,j;

   for (i = 0; i < 8; i++)
   {
      playboard[i][0] =  0;
      playboard[i][1] =  1;
      playboard[i][2] =  0;
      playboard[i][3] =  1;
      playboard[i][4] =  0;
      playboard[i][5] =  1;
      playboard[i][6] =  0;
      playboard[i][7] =  1;
   }

   spi_init();
   delay_ms(1);
   max7219_init();
   delay_ms(1);

   for (i = 1; i < 9; i++)
   {
      delay_ms(1);
   }

   while (1)
   {

      for (j = 0; j < 8; j++)
      {
         matrix_lines[j] = 0;
         for (i = 0; i < 8; i++)
         {
               {
                  matrix_lines[j] |= (playboard[j][i] << (7 - i));
               }
         }
      }

      for(i = 0; i < 8; i++)
      {
         delay_ms(1);
         max7219_send(i + 1, matrix_lines[i] );
      }
      delay_ms(1000);
   }

}   
